[package]
name = "linux-storage-manager-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "storagemgr"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
lsm-core = { path = "../core" }
lsm-discovery = { path = "../discovery" }
lsm-planner = { path = "../planner" }
lsm-tui = { path = "../tui" }
serde_json.workspace = true
